services:
    _defaults:
        autowire: true
        autoconfigure: true

    #Layout providers
    smile_product_review.layout.data_provider.product_data:
        class: Smile\Bundle\ProductReviewBundle\Layout\DataProvider\ProductDataProvider
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@smile_product_review.manager.smile_product_review_manager'
        tags:
            - { name: layout.data_provider, alias: smile_product }

    smile_product_review.layout.data_provider.product_review_form:
        class: Smile\Bundle\ProductReviewBundle\Layout\DataProvider\ProductReviewFormProvider
        arguments:
            - '@form.factory'
            - '@router.default'
            - '@smile_product_review.form.extension.product_review_type_extension'
        tags:
            - { name: layout.data_provider, alias: product_review_form }

    #Managers
    smile_product_review.manager.smile_product_review_manager:
        class: Smile\Bundle\ProductReviewBundle\Manager\ProductReviewManager
        arguments:
            - '@doctrine.orm.entity_manager'

    #Subscribers
    smile_product_review.subscriber.set_product_rating:
        class: Smile\Bundle\ProductReviewBundle\EventListener\SetProductRatingSubscriber
        arguments:
            - '@smile_product_review.manager.smile_product_review_manager'
        tags:
            - { name: doctrine.event_subscriber }

    smile_product_review.subscriber.set_product_review_organization_and_owner:
        class: Smile\Bundle\ProductReviewBundle\EventListener\SetProductReviewOrganizationAndOwnerSubscriber
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oro_security.token_accessor'
        tags:
            - { name: doctrine.event_subscriber }

    #Listeners
    smile_product_review.event_listener.frontend.datagrid.product:
        class: Smile\Bundle\ProductReviewBundle\EventListener\FrontendProductDatagridListener
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_datagrid.provider.selected_fields'
            - '@smile_product_review.manager.smile_product_review_manager'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.search_datasource.result.after.frontend-product-search-grid, method: onResultAfter }
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.frontend-product-search-grid, method: onBuildBefore }

    smile_product_review.event_listener.website_search_product_indexer:
        class: Smile\Bundle\ProductReviewBundle\EventListener\WebsiteSearchProductIndexerListener
        arguments:
            - '@oro_website_search.manager.website_context_manager'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: kernel.event_listener, event: oro_website_search.event.index_entity.product, method: onWebsiteSearchIndex }

    #FormTypes
    smile_product_review.form.type.product_review_type:
        class: Smile\Bundle\ProductReviewBundle\Form\Type\ProductReviewType
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
            - '@smile_product_review.provider.product_rating_choice_provider'
            - '@smile_product_review.form.extension.product_review_type_extension'
        tags:
            - { name: form.type }

    #Providers
    smile_product_review.provider.product_status_provider:
        class: Smile\Bundle\ProductReviewBundle\Provider\ProductReviewStatusProvider
        public: true

    smile_product_review.provider.product_rating_choice_provider:
        class: Smile\Bundle\ProductReviewBundle\Provider\ProductReviewRatingChoiceProvider

    #For datagrid
    smile_product_review.datagrid.product_review_list:
        class: Smile\Bundle\ProductReviewBundle\Datagrid\ProductReviewList
        public: true

    #Factory
    smile_product_review.factory.product_review:
        class: Smile\Bundle\ProductReviewBundle\Entity\Factory\ProductReviewFactory
        public: true

    #Form type extension
    smile_product_review.form.extension.product_review_type_extension:
        class: Smile\Bundle\ProductReviewBundle\Form\Extension\ProductReviewTypeExtension
        calls:
            - [setConfigManager, ['@oro_config.user']]
        tags:
            - { name: form.type_extension, extended_type: Smile\Bundle\ProductReviewBundle\Form\Type\ProductReviewType }
