system_configuration:
    fields:
        product_review.protect_product_review_form:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            options:
                label: 'smile.product_review.system_configuration.fields.enable_google_recaptcha.label'
                required: false
                resettable: false

    tree:
        system_configuration:
            platform:
                children:
                    integrations:
                        children:
                            hack_oro_recaptcha:
                                children:
                                    protected_features:
                                        children:
                                            - product_review.protect_product_review_form
